//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPulse.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventPulse.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add_new_event.
        /// </summary>
        internal static string Add_new_event {
            get {
                return ResourceManager.GetString("Add_new_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App_name.
        /// </summary>
        internal static string App_name {
            get {
                return ResourceManager.GetString("App_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit_event.
        /// </summary>
        internal static string Edit_event {
            get {
                return ResourceManager.GetString("Edit_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event_date.
        /// </summary>
        internal static string Event_date {
            get {
                return ResourceManager.GetString("Event_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event_description.
        /// </summary>
        internal static string Event_description {
            get {
                return ResourceManager.GetString("Event_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event_title.
        /// </summary>
        internal static string Event_title {
            get {
                return ResourceManager.GetString("Event_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_started.
        /// </summary>
        internal static string Get_started {
            get {
                return ResourceManager.GetString("Get_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No_records.
        /// </summary>
        internal static string No_records {
            get {
                return ResourceManager.GetString("No_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
